# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hemingway17"
license = "MIT"
licenselink = "https://github.com/michaelsharman/hemingway17/blob/master/LICENSE.md"
description = "Really minimal blog theme for hugo"
homepage = "https://github.com/michaelsharman/hemingway17"
tags = ["blog", "font awesome", "highlight.js"]
features = ["html5", "css3", "tags"]
min_version = 0.16

[author]
  name = "Michael Sharman"
  homepage = "https://github.com/michaelsharman"
