baseurl = "http://chapter31.com"
languageCode = "en"
title = "chapter31"
theme = "hemingway17"
copyright = "&copy; <a href=\"http://michaelsharman.com\">Michael Sharman</a> 2017"
disqusShortname = ""
googleAnalytics = "UA-306772-2"
description = "Your personal description"
keywords = ["keyword1", "keyword2"]

[taxonomies]
tag = "tags"
category = "categories"

[params]

[params.highlight]
style = "ocean"
languages = ["javascript"]

[[params.social]]
url = "http://michaelsharman.com"
fa_icon = "fa-user-circle"
label = "michaelsharman.com"

[[params.social]]
url = "https://github.com/michaelsharman"
fa_icon = "fa-github"
label = "GitHub"

[[params.social]]
url = "https://twitter.com/michaelsharman"
fa_icon = "fa-twitter"
label = "Twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
label = "RSS"
